// Public types facade for the dashboard.
//
// Wire DTOs (`MemoryDto`, `GraphResponseDto`, `VestigeEvent`, …) are
// generated by ts-rs from Rust structs in `crates/vestige-mcp/src/dashboard/wire/`
// and imported here under their legacy names so existing call sites
// don't have to change. To regenerate after a backend change:
//
//   cargo test -p vestige-mcp --lib dashboard
//
// Anything below the "// === Dashboard-only types ===" marker has no
// backend counterpart — UI-only constants, color tables, helper unions,
// and types for endpoints that still pass `serde_json::Value` through
// (dream / explore / FSRS rating literals).

import type {
  ConfidenceEntryDto,
  ConfidenceResultDto,
  ConsolidationResultDto,
  CreateIntentionResponseDto,
  DecisionDto,
  DecisionListResponseDto,
  DeepRefContradictionDto,
  DeepRefEvidenceDto,
  DeepRefEvolutionDto,
  DeepReferenceResultDto,
  DeepRefInsightDto,
  DeepRefSupersededDto,
  EndangeredMemoryDto,
  ExploreResponseDto,
  ExploreResultDto,
  VestigeEvent as GeneratedVestigeEvent,
  GraphEdgeDto,
  GraphNodeDto,
  GraphResponseDto,
  HealthCheckDto,
  HubDto,
  HubListResponseDto,
  InsightDto,
  InsightListResponseDto,
  IntentionItemDto,
  IntentionListResponseDto,
  MemoryChangelogDto,
  MemoryChangelogEntryDto,
  MemoryDto,
  MemoryListResponseDto,
  MemoryStatusDto,
  MemoryUpdateResultDto,
  PredictedMemoryDto,
  PredictResponseDto,
  ReflectInsightDto,
  ReflectResultDto,
  RetentionBucketDto,
  RetentionDistributionDto,
  ReviewItemDto,
  ReviewQueueResponseDto,
  ReviewResultDto,
  SearchResultDto,
  SystemStatsDto,
  TemporalEntryDto,
  TemporalResultDto,
  TimelineDayDto,
  TimelineMemoryDto,
  TimelineResponseDto,
} from './generated';

// Re-export everything generated, in case a caller wants the raw DTO names.
export * from './generated';

// ---------------------------------------------------------------------------
// Aliases — legacy dashboard-side names mapped to the generated DTOs.
// These two-line aliases mean every call site keeps importing
// `Memory`, `SearchResult`, etc., and gets compile errors automatically
// when the wire DTO drifts.
// ---------------------------------------------------------------------------

export type Memory = MemoryDto;
export type SearchResult = SearchResultDto;
export type MemoryListResponse = MemoryListResponseDto;
export type MemoryStatus = MemoryStatusDto;
export type MemoryUpdateResult = MemoryUpdateResultDto;
export type MemoryChangelog = MemoryChangelogDto;
export type MemoryChangelogEntry = MemoryChangelogEntryDto;
export type ReviewResult = ReviewResultDto;
export type ReviewItem = ReviewItemDto;
export type ReviewQueueResponse = ReviewQueueResponseDto;
export type SystemStats = SystemStatsDto;
export type HealthCheck = HealthCheckDto;
export type TimelineDay = TimelineDayDto;
export type TimelineMemory = TimelineMemoryDto;
export type TimelineResponse = TimelineResponseDto;
export type GraphNode = GraphNodeDto;
export type GraphEdge = GraphEdgeDto;
export type GraphResponse = GraphResponseDto;
export type RetentionDistribution = RetentionDistributionDto;
export type RetentionBucket = RetentionBucketDto;
export type EndangeredMemory = EndangeredMemoryDto;
export type ConsolidationResult = ConsolidationResultDto;
export type IntentionItem = IntentionItemDto;
export type IntentionListResponse = IntentionListResponseDto;
export type CreateIntentionResponse = CreateIntentionResponseDto;
export type ReflectResult = ReflectResultDto;
export type ReflectInsight = ReflectInsightDto;
export type TemporalEntry = TemporalEntryDto;
export type TemporalResult = TemporalResultDto;
export type ConfidenceResult = ConfidenceResultDto;
export type ConfidenceEntry = ConfidenceEntryDto;
export type PredictedMemory = PredictedMemoryDto;
export type PredictResponse = PredictResponseDto;
export type ExploreResult = ExploreResultDto;
export type ExploreResponse = ExploreResponseDto;
export type Decision = DecisionDto;
export type DecisionListResponse = DecisionListResponseDto;
export type Insight = InsightDto;
export type InsightListResponse = InsightListResponseDto;
export type Hub = HubDto;
export type HubListResponse = HubListResponseDto;
export type DeepReferenceResult = DeepReferenceResultDto;
export type DeepRefEvidence = DeepRefEvidenceDto;
export type DeepRefContradiction = DeepRefContradictionDto;
export type DeepRefSuperseded = DeepRefSupersededDto;
export type DeepRefEvolution = DeepRefEvolutionDto;
export type DeepRefInsight = DeepRefInsightDto;

// VestigeEvent: the generated discriminated union is strictly better
// (per-variant `data` types instead of `Record<string, unknown>`), so
// re-export it under the legacy name.
export type VestigeEvent = GeneratedVestigeEvent;

/**
 * The set of `type` discriminators on `VestigeEvent`. Includes the
 * synthetic `"Connected"` event the dashboard injects after the WS
 * socket opens — never sent by the backend, hence the union extension.
 */
export type VestigeEventType = VestigeEvent['type'] | 'Connected';

/**
 * `VestigeEvent` plus a stable monotonic id for React keying. The
 * client assigns `_id` at receive time — it never crosses the wire.
 */
export type IdentifiedEvent = VestigeEvent & { _id: number };

// ---------------------------------------------------------------------------
// === Dashboard-only types ===
// Things that have no DTO yet (dream still streams through `Json<Value>`,
// FSRS rating is just a literal union, intention helpers are derived from
// the DTO).
// ---------------------------------------------------------------------------

/** FSRS-6 rating values. 1=Again (forgot), 2=Hard, 3=Good, 4=Easy. */
export type FsrsRating = 1 | 2 | 3 | 4;

/** Intention trigger discriminator — sent on POST, never inspected on GET. */
export type TriggerType = 'context' | 'time' | 'event';
export type IntentionPriority = IntentionItem['priority'];
export type IntentionStatus = IntentionItem['status'];

/**
 * Temporal-versioning action discriminator. Mirrors the `action` arg
 * accepted by `tools::temporal` and the value echoed back in
 * `TemporalResultDto.action`. Kept as a literal union (not just
 * `TemporalResult["action"]: string`) because the dashboard's
 * `<TemporalPage>` switches on it exhaustively.
 */
export type TemporalAction = 'current' | 'expired' | 'history' | 'invalidate';

/**
 * Output of `tools/dream::execute`. Still hand-typed because the dream
 * engine emits a complex nested shape that hasn't been DTO-fied yet —
 * see `dashboard/handlers/cognitive.rs::trigger_dream`.
 *
 * TODO(Q-vestige-typesafety): port to `wire::dream` and replace this
 * block with `export type DreamResult = DreamResultDto`.
 */
export interface DreamResult {
  status: string;
  memoriesReplayed: number;
  wakingTagsProcessed: number;
  wakingTagsCleared: number;
  connectionsPersisted: number;
  insights: DreamInsight[];
  contradictions: ContradictionPair[];
  /**
   * Currently always empty — engine only counts demotions, not their IDs.
   * Kept on the wire so the dashboard can render the count consistently
   * with the strengthened/downscaled stats.
   */
  memoriesDemoted: string[];
  phases: DreamPhase[];
  stats: DreamStats;
}

export interface DreamPhase {
  phase: string;
  durationMs: number;
  memoriesProcessed: number;
  actions: string[];
}

export interface DreamStats {
  creativeConnectionsFound: number;
  connectionsPersisted: number;
  memoriesStrengthened: number;
  memoriesDownscaled: number;
  emotionalProcessed: number;
  contradictionsFound: number;
  insightsGenerated: number;
  durationMs: number;
}

export interface DreamInsight {
  type: string;
  insight: string;
  sourceMemories: string[];
  confidence: number;
  noveltyScore: number;
}

/**
 * A pair of memories the dream engine flagged as contradictory.
 * Symmetric — neither side is the "winner". Resolution is a UI concern.
 */
export interface ContradictionPair {
  memoryA: string;
  memoryB: string;
  confidence: number;
  insight: string;
}

/**
 * Local helper for the importance widget — derives directly from the
 * generated `ImportanceScoreDto.composite` to drive the save/skip CTA.
 * Kept here because the rule lives on the dashboard side.
 */
export type ImportanceRecommendation = 'save' | 'skip';

/**
 * UI-side projection of `ImportanceScoreDto` with a derived recommendation.
 * Use `toImportanceScore(dto)` to construct it (in `lib/importance.ts`).
 */
export interface ImportanceScore {
  composite: number;
  channels: {
    novelty: number;
    arousal: number;
    reward: number;
    attention: number;
  };
  recommendation: ImportanceRecommendation;
}

// ---------------------------------------------------------------------------
// === Color tables ===
// Pure presentation — stay in the types module because every component
// that imports the entity also imports its color.
// ---------------------------------------------------------------------------

export const NODE_TYPE_COLORS: Record<string, string> = {
  fact: '#00A8FF',
  concept: '#9D00FF',
  event: '#FFB800',
  person: '#00FFD1',
  place: '#00D4FF',
  note: '#8B95A5',
  pattern: '#FF3CAC',
  decision: '#FF4757',
  insight: '#C084FC',
  hub: '#14E8C6',
};

export const EVENT_TYPE_COLORS: Record<VestigeEventType, string> = {
  Connected: '#10b981',
  MemoryCreated: '#00FFD1',
  MemoryUpdated: '#00A8FF',
  MemoryDeleted: '#FF4757',
  MemoryPromoted: '#00FF88',
  MemoryDemoted: '#FF6B35',
  SearchPerformed: '#818CF8',
  DreamStarted: '#9D00FF',
  DreamProgress: '#B44AFF',
  DreamCompleted: '#C084FC',
  ConsolidationStarted: '#FFB800',
  ConsolidationCompleted: '#FF9500',
  RetentionDecayed: '#FF4757',
  ConnectionDiscovered: '#00D4FF',
  ActivationSpread: '#14E8C6',
  ImportanceScored: '#FF3CAC',
  Heartbeat: '#8B95A5',
};

/**
 * Three-tier retention color: green > 0.7, amber > 0.4, red below.
 * Thresholds match the FSRS-6 desired-retention defaults; if the engine
 * changes its `min_retention` policy we should bump these too.
 */
export function retentionColor(r: number): string {
  if (r > 0.7) return '#10b981';
  if (r > 0.4) return '#f59e0b';
  return '#ef4444';
}

export const EPISTEMIC_STATUS_COLORS: Record<string, string> = {
  world: '#00A8FF',
  experience: '#FFB800',
  observation: '#FF3CAC',
  opinion: '#9D00FF',
};

export const MEMORY_SYSTEM_COLORS: Record<string, string> = {
  episodic: '#FFB800',
  semantic: '#00A8FF',
  procedural: '#00FFD1',
};
