/**
 * Hermetic tests for the npm wrapper's integrity gate.
 *
 * No network: the checksum *fetch* is an injected outcome and the archives are
 * local tarballs built in a temp dir. What is exercised is the production
 * decision code (`installWithChecksum`, `verifyArchive`) plus the real
 * `postinstall.js` skip path.
 *
 * Run: node --test scripts/binary-install.test.js
 * (also wired into CI as a step of the `metadata` job)
 */

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync, spawnSync } = require('node:child_process');

const {
  ChecksumError,
  checksumsMatch,
  classifyChecksumResponse,
  installWithChecksum,
  parseChecksum,
  sha256File,
  verifyArchive,
} = require('./binary-install');

const HAS_TAR = spawnSync('tar', ['--version'], { stdio: 'ignore' }).status === 0;

function tempDir(prefix) {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

/** Build a real gzip tarball containing a fake `vestige-mcp` binary. */
function makeArchive(dir, name = 'vestige-mcp-test-target.tar.gz') {
  const payload = path.join(dir, 'payload');
  fs.mkdirSync(payload, { recursive: true });
  fs.writeFileSync(path.join(payload, 'vestige-mcp'), '#!/bin/sh\necho fake binary\n', { mode: 0o755 });

  const archivePath = path.join(dir, name);
  execFileSync('tar', ['-czf', archivePath, '-C', payload, 'vestige-mcp']);
  return archivePath;
}

/** `sha256sum`-style asset contents for an existing file. */
function checksumAsset(archivePath) {
  return `${sha256File(archivePath)}  ${path.basename(archivePath)}\n`;
}

test('parseChecksum reads sha256sum output and ignores noise', () => {
  const digest = 'a'.repeat(64);
  assert.equal(parseChecksum(`${digest}  vestige-mcp.tar.gz\n`), digest);
  assert.equal(parseChecksum(`# generated by release.yml\n\n${digest} *file.zip\n`), digest);
  assert.equal(parseChecksum(`${digest.toUpperCase()}  file\n`), digest, 'normalises case');
  assert.equal(parseChecksum(''), null);
  assert.equal(parseChecksum('not a checksum'), null);
  assert.equal(parseChecksum(`${'a'.repeat(63)}  short\n`), null);
  assert.equal(parseChecksum(undefined), null);
});

test('checksumsMatch is a constant-time compare that never throws on length mismatch', () => {
  const digest = 'b'.repeat(64);
  assert.equal(checksumsMatch(digest, digest), true);
  assert.equal(checksumsMatch(digest.toUpperCase(), digest), true);
  assert.equal(checksumsMatch(digest, 'c'.repeat(64)), false);
  assert.equal(checksumsMatch(digest, 'b'.repeat(63)), false, 'different lengths must not throw');
  assert.equal(checksumsMatch(null, digest), false);
});

test('classifyChecksumResponse separates "no asset" from "unreachable"', () => {
  assert.deepEqual(classifyChecksumResponse(200, 'x'), { kind: 'ok', text: 'x' });
  assert.equal(classifyChecksumResponse(404, '').kind, 'missing');
  assert.equal(classifyChecksumResponse(410, '').kind, 'missing');
  assert.equal(classifyChecksumResponse(500, '').kind, 'unavailable');
  assert.equal(classifyChecksumResponse(403, '').kind, 'unavailable');
});

test('sha256File matches the digest of the same bytes', () => {
  const file = path.join(tempDir('vestige-sha-'), 'payload.bin');
  const bytes = Buffer.from('vestige\n');
  fs.writeFileSync(file, bytes);
  const expected = crypto.createHash('sha256').update(bytes).digest('hex');
  assert.equal(sha256File(file), expected);
});

test('a matching checksum extracts the archive', { skip: !HAS_TAR }, () => {
  const dir = tempDir('vestige-ok-');
  const archivePath = makeArchive(dir);
  const targetDir = path.join(dir, 'bin');
  fs.mkdirSync(targetDir);

  const report = installWithChecksum({
    outcome: { kind: 'ok', text: checksumAsset(archivePath) },
    archivePath,
    targetDir,
    warn: () => assert.fail('a verified install must not warn'),
  });

  assert.equal(report.verified, true);
  assert.equal(report.checksum, sha256File(archivePath));
  assert.ok(fs.existsSync(path.join(targetDir, 'vestige-mcp')), 'binary extracted');
});

test('a MISMATCHED checksum aborts the install and never runs the extractor', () => {
  const dir = tempDir('vestige-mismatch-');
  const archivePath = makeArchive(dir);
  const targetDir = path.join(dir, 'bin');
  fs.mkdirSync(targetDir);

  let extractorCalls = 0;
  const run = () => {
    extractorCalls += 1;
  };

  assert.throws(
    () =>
      installWithChecksum({
        outcome: { kind: 'ok', text: `${'0'.repeat(64)}  ${path.basename(archivePath)}\n` },
        archivePath,
        targetDir,
        run,
      }),
    (err) => {
      assert.ok(err instanceof ChecksumError, 'must be a ChecksumError');
      assert.match(err.message, /SHA-256 mismatch/);
      assert.match(err.message, /NOT extracted/);
      return true;
    },
  );

  assert.equal(extractorCalls, 0, 'fail-closed: the extractor must not be invoked');
  assert.deepEqual(fs.readdirSync(targetDir), [], 'nothing may be unpacked');
});

test('a mismatched checksum leaves the target directory empty with the real extractor', { skip: !HAS_TAR }, () => {
  const dir = tempDir('vestige-mismatch-real-');
  const archivePath = makeArchive(dir);
  const targetDir = path.join(dir, 'bin');
  fs.mkdirSync(targetDir);

  assert.throws(
    () =>
      installWithChecksum({
        outcome: { kind: 'ok', text: `${'f'.repeat(64)}  ${path.basename(archivePath)}\n` },
        archivePath,
        targetDir,
      }),
    ChecksumError,
  );

  assert.deepEqual(fs.readdirSync(targetDir), []);
});

test('a truncated/absent digest in a published asset is treated as fail-closed', () => {
  const dir = tempDir('vestige-garbage-');
  const archivePath = makeArchive(dir);
  const targetDir = path.join(dir, 'bin');
  fs.mkdirSync(targetDir);

  let extractorCalls = 0;
  assert.throws(
    () =>
      installWithChecksum({
        outcome: { kind: 'ok', text: '<html>rate limited</html>' },
        archivePath,
        targetDir,
        run: () => {
          extractorCalls += 1;
        },
      }),
    ChecksumError,
  );
  assert.equal(extractorCalls, 0);
});

test('verifyArchive returns both digests when they agree', () => {
  const dir = tempDir('vestige-verify-');
  const archivePath = makeArchive(dir);
  const { expected, actual } = verifyArchive(archivePath, checksumAsset(archivePath));
  assert.equal(expected, actual);
});

for (const outcome of [{ kind: 'missing' }, { kind: 'unavailable', reason: 'HTTP 500' }]) {
  test(`no usable checksum (${outcome.kind}) extracts but warns loudly`, { skip: !HAS_TAR }, () => {
    const dir = tempDir(`vestige-${outcome.kind}-`);
    const archivePath = makeArchive(dir);
    const targetDir = path.join(dir, 'bin');
    fs.mkdirSync(targetDir);

    const warnings = [];
    const report = installWithChecksum({
      outcome,
      archivePath,
      targetDir,
      warn: (message) => warnings.push(message),
    });

    assert.equal(report.verified, false, 'install reports it was not verified');
    assert.equal(warnings.length, 1);
    assert.match(warnings[0], /integrity .* was NOT verified/i);
    assert.ok(fs.existsSync(path.join(targetDir, 'vestige-mcp')), 'legacy release still installs');
  });
}

test('the wrapper has no extraction path that bypasses verification', () => {
  const source = fs.readFileSync(path.join(__dirname, 'postinstall.js'), 'utf8');
  assert.match(source, /installWithChecksum\(/, 'the wrapper must verify through the shared helper');
  assert.doesNotMatch(source, /\bextract\(/, 'postinstall.js must not extract on its own');
  assert.doesNotMatch(
    source,
    /child_process|execSync|execFileSync|Expand-Archive|tar -xzf/,
    'unpacking must live in binary-install.js, behind verifyArchive',
  );
});

test('VESTIGE_SKIP_BINARY_DOWNLOAD=1 short-circuits the wrapper without network access', () => {
  const result = spawnSync(process.execPath, [path.join(__dirname, 'postinstall.js')], {
    env: { ...process.env, VESTIGE_SKIP_BINARY_DOWNLOAD: '1' },
    encoding: 'utf8',
  });

  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /skipping the binary download/i);
});
