//! Knowledge Node - The fundamental unit of memory
//!
//! Each node represents a discrete piece of knowledge with:
//! - Content and metadata
//! - FSRS-6 scheduling state
//! - Dual-strength retention model
//! - Temporal validity (bi-temporal)
//! - Embedding metadata

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ============================================================================
// NODE TYPES
// ============================================================================

/// Types of knowledge nodes
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum NodeType {
    /// A discrete fact or piece of information
    #[default]
    Fact,
    /// A concept or abstract idea
    Concept,
    /// A procedure or how-to knowledge
    Procedure,
    /// An event or experience
    Event,
    /// A relationship between entities
    Relationship,
    /// A quote or verbatim text
    Quote,
    /// Code or technical snippet
    Code,
    /// A question to be answered
    Question,
    /// User insight or reflection
    Insight,
    /// Architectural / design / product decision with structured matrix
    /// payload stored under `extra_json.decision` (Proposal C). Legacy
    /// free-form Markdown decisions also map to this variant.
    Decision,
    /// Topic-hub summary node that aggregates a cluster of related memories
    /// (Proposal A). Carries derived content and is regenerated by the
    /// dream cycle rather than written by hand.
    Hub,
}

impl NodeType {
    /// Convert to string representation
    pub fn as_str(&self) -> &'static str {
        match self {
            NodeType::Fact => "fact",
            NodeType::Concept => "concept",
            NodeType::Procedure => "procedure",
            NodeType::Event => "event",
            NodeType::Relationship => "relationship",
            NodeType::Quote => "quote",
            NodeType::Code => "code",
            NodeType::Question => "question",
            NodeType::Insight => "insight",
            NodeType::Decision => "decision",
            NodeType::Hub => "hub",
        }
    }

    /// Parse from string name
    pub fn parse_name(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "fact" => NodeType::Fact,
            "concept" => NodeType::Concept,
            "procedure" => NodeType::Procedure,
            "event" => NodeType::Event,
            "relationship" => NodeType::Relationship,
            "quote" => NodeType::Quote,
            "code" => NodeType::Code,
            "question" => NodeType::Question,
            "insight" => NodeType::Insight,
            "decision" => NodeType::Decision,
            "hub" => NodeType::Hub,
            _ => NodeType::Fact,
        }
    }
}

impl std::fmt::Display for NodeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// ============================================================================
// MEMORY KIND (ENGRAM-style typed memory)
// ============================================================================

/// Memory kind classifies *how* the content is shaped and retrieved.
///
/// Orthogonal to [`NodeType`]: a NodeType says what the content is *about*
/// (a fact, a procedure, an event), while a MemoryKind says how the content
/// was *recorded* — was it raw input, or was it distilled by an extractor
/// into an atomic, self-contained statement?
///
/// Per-kind retrieval (route temporal questions to `Episodic`, attribute
/// questions to `Semantic`, etc.) is opt-in and lives in the search layer;
/// this enum just carries the metadata so the search layer can filter on
/// it without reparsing content.
///
/// LoCoMo PoC results (full N=1540): replacing raw chunks with extracted
/// facts alone loses −6.88 pp. Augmenting raw chunks with extracted facts
/// side-by-side wins +3.96 pp. See `docs/TYPED-MEMORY-DESIGN.md`.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum MemoryKind {
    /// Raw input — dialogue, chunks, anything not classified by an
    /// extractor. Default for back-compat: existing memories migrate here.
    #[default]
    Raw,
    /// A stable attribute or relationship ("Caroline lives in Berlin").
    /// Carries `subject`, `predicate`, `object`.
    Semantic,
    /// A specific event tied to a date/time ("Caroline attended X on Y").
    /// Carries `subject` and `episodic_at`.
    Episodic,
    /// A habit, frequency, or recurring pattern ("X goes to Y every Tuesday").
    /// Carries `subject` and `procedural_frequency`.
    Procedural,
    /// A multi-item enumeration captured as one statement. Solves
    /// list-style questions ("What activities does X do?"). Carries
    /// `subject` only; items live in `content`.
    Aggregate,
}

impl MemoryKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            MemoryKind::Raw => "raw",
            MemoryKind::Semantic => "semantic",
            MemoryKind::Episodic => "episodic",
            MemoryKind::Procedural => "procedural",
            MemoryKind::Aggregate => "aggregate",
        }
    }

    pub fn parse(s: &str) -> Self {
        match s.to_ascii_lowercase().as_str() {
            "semantic" => MemoryKind::Semantic,
            "episodic" => MemoryKind::Episodic,
            "procedural" => MemoryKind::Procedural,
            "aggregate" => MemoryKind::Aggregate,
            _ => MemoryKind::Raw,
        }
    }
}

impl std::fmt::Display for MemoryKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// ============================================================================
// KNOWLEDGE NODE
// ============================================================================

/// Where a memory's *valid time* window stands at one instant.
///
/// The three clocks are deliberately separate: `recorded_at` is when we wrote a
/// memory down, `valid_from`/`valid_until` are when its claim about the world
/// held, and `last_accessed` is when we last read it. A reader who asks "what
/// did we believe at instant T" is asking a *record-time* question, and
/// filtering that answer on valid time as well would return a set that answers
/// neither question. The read path therefore reports this value next to the
/// result instead, so the caller can apply the valid-time reading themselves.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ValidityAt {
    /// Both bounds were open: the memory carried no validity window at all.
    Unbounded,
    /// `valid_from` is after the instant — the claim had not started holding.
    NotYetTrue,
    /// The instant falls inside the window.
    True,
    /// `valid_until` is at or before the instant — the claim had stopped holding.
    Expired,
}

impl ValidityAt {
    /// The name this value is reported under on the wire.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Unbounded => "unbounded",
            Self::NotYetTrue => "not_yet_true",
            Self::True => "true",
            Self::Expired => "expired",
        }
    }
}

impl std::fmt::Display for ValidityAt {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

/// A knowledge node in the memory graph
///
/// Combines multiple memory science models:
/// - FSRS-6 for optimal review scheduling
/// - Bjork dual-strength for realistic forgetting
/// - Temporal validity for time-sensitive knowledge
///
/// **API stability:** This struct is exhaustively constructible while
/// `vestige-core` is pre-1.0. When stabilising we may reintroduce
/// `#[non_exhaustive]`; until then tests, fixtures and downstream crates may
/// build instances with `KnowledgeNode { ..Default::default() }`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KnowledgeNode {
    /// Unique identifier (UUID v4)
    pub id: String,
    /// The actual content/knowledge
    pub content: String,
    /// Type of knowledge (fact, concept, procedure, etc.)
    pub node_type: String,
    /// When the node was created
    pub created_at: DateTime<Utc>,
    /// When the node was last modified
    pub updated_at: DateTime<Utc>,
    /// When the node was last accessed/reviewed
    pub last_accessed: DateTime<Utc>,
    /// When this memory was *recorded* — when we wrote it down.
    ///
    /// Distinct from `created_at` (row birth) and from `last_accessed`
    /// (refreshed by every search hit, so it carries no claim about age).
    /// Immutable by contract: no update path, and no strengthening, decay or
    /// consolidation pass may move it, because "when did we learn this" is the
    /// only anchor a reader has for how the picture changed over time.
    #[serde(default = "Utc::now")]
    pub recorded_at: DateTime<Utc>,

    // ========== FSRS-6 State (21 parameters) ==========
    /// Memory stability (days until 90% forgetting probability)
    pub stability: f64,
    /// Inherent difficulty (1.0 = easy, 10.0 = hard)
    pub difficulty: f64,
    /// Number of successful reviews
    pub reps: i32,
    /// Number of lapses (forgotten after learning)
    pub lapses: i32,

    // ========== Dual-Strength Model (Bjork & Bjork 1992) ==========
    /// Storage strength - accumulated with practice, never decays
    pub storage_strength: f64,
    /// Retrieval strength - current accessibility, decays over time
    pub retrieval_strength: f64,
    /// Combined retention score (0.0 - 1.0)
    pub retention_strength: f64,

    // ========== Emotional Memory ==========
    /// Sentiment polarity (-1.0 to 1.0)
    pub sentiment_score: f64,
    /// Sentiment intensity (0.0 to 1.0) - affects stability
    pub sentiment_magnitude: f64,

    // ========== Scheduling ==========
    /// Next scheduled review date
    pub next_review: Option<DateTime<Utc>>,

    // ========== Provenance ==========
    /// Source of the knowledge (URL, file, conversation, etc.)
    pub source: Option<String>,
    /// Tags for categorization
    pub tags: Vec<String>,

    // ========== Temporal Memory (Bi-temporal) ==========
    /// When this knowledge became valid
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<DateTime<Utc>>,
    /// When this knowledge stops being valid
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<DateTime<Utc>>,

    // ========== Utility Tracking (MemRL v1.9.0) ==========
    /// Utility score = times_useful / times_retrieved (0.0 to 1.0)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub utility_score: Option<f64>,
    /// Number of times this memory was retrieved in search
    #[serde(skip_serializing_if = "Option::is_none")]
    pub times_retrieved: Option<i32>,
    /// Number of times this memory was subsequently useful
    #[serde(skip_serializing_if = "Option::is_none")]
    pub times_useful: Option<i32>,

    // ========== Emotional Memory (v2.0.0) ==========
    /// Emotional valence: -1.0 (negative) to 1.0 (positive)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub emotional_valence: Option<f64>,
    /// Flashbulb memory flag: ultra-high-fidelity encoding
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flashbulb: Option<bool>,

    // ========== Temporal Hierarchy (v2.0.0) ==========
    /// Temporal level for summary nodes: None=leaf, "daily"/"weekly"/"monthly"
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temporal_level: Option<String>,

    // ========== Semantic Embedding ==========
    /// Whether this node has an embedding vector
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_embedding: Option<bool>,
    /// Which model generated the embedding
    #[serde(skip_serializing_if = "Option::is_none")]
    pub embedding_model: Option<String>,

    // ========== Provenance (v3.1.0 Content Intelligence) ==========
    /// Structured provenance metadata: session, agent, derivation chain, preprocessing artifacts
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provenance: Option<serde_json::Value>,

    // ========== Structured payload (v3.4.0 — typed extensions) ==========
    /// Free-form JSON for typed extensions that don't deserve their own
    /// column. The `codebase` tool stores the structured decision matrix
    /// under `extra_json.decision`; future extensions (hubs, insights)
    /// can claim other top-level keys without another migration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra_json: Option<serde_json::Value>,

    // ========== Typed Memory (v3.3.0 — ENGRAM-style) ==========
    /// Memory kind classifies *how* the content is shaped and retrieved.
    /// Defaults to `Raw` for back-compat; extractors set this to a more
    /// specific kind when they distill content into atomic facts.
    #[serde(default)]
    pub memory_kind: MemoryKind,
    /// Subject the fact is about (proper noun like "Caroline"). Only set
    /// for non-Raw kinds, used by subject-aware retrieval.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Predicate for semantic facts ("lives in", "has", "is"). Optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub predicate: Option<String>,
    /// Object for semantic facts ("Berlin", "a dog named Max"). Optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Absolute timestamp for `Episodic` memories. Anchors "when did X happen"
    /// queries even when the content uses relative phrasing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub episodic_at: Option<DateTime<Utc>>,
    /// Frequency descriptor for `Procedural` memories ("weekly",
    /// "every Tuesday", "monthly"). Free-form string for now; later
    /// versions may parse into a structured Frequency enum.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub procedural_frequency: Option<String>,

    // ========== Self-containedness (V18) ==========
    /// What the write-time self-containedness gate said about this memory:
    /// `Some(true)` it ran and the memory stands on its own, `Some(false)` it
    /// ran and flagged the memory as needing the conversation it came from.
    ///
    /// `None` is not "clean": it means no gate ran (a row written before V18, or
    /// by a writer that is not `smart_ingest`). The distinction is the whole
    /// point of the column — a memory that needs context must be findable later,
    /// and a store that reports "no flags" must not be reporting on rows it
    /// never checked.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub self_contained: Option<bool>,
    /// The findings behind a `self_contained: false`, verbatim as the gate
    /// reported them, so a reader learns what to fix and not only that
    /// something is wrong.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub self_contained_findings: Option<serde_json::Value>,
}

impl Default for KnowledgeNode {
    fn default() -> Self {
        let now = Utc::now();
        Self {
            id: String::new(),
            content: String::new(),
            node_type: "fact".to_string(),
            created_at: now,
            updated_at: now,
            last_accessed: now,
            recorded_at: now,
            stability: 2.5,
            difficulty: 5.0,
            reps: 0,
            lapses: 0,
            storage_strength: 1.0,
            retrieval_strength: 1.0,
            retention_strength: 1.0,
            sentiment_score: 0.0,
            sentiment_magnitude: 0.0,
            next_review: None,
            source: None,
            tags: vec![],
            valid_from: None,
            valid_until: None,
            utility_score: None,
            times_retrieved: None,
            times_useful: None,
            emotional_valence: None,
            flashbulb: None,
            temporal_level: None,
            has_embedding: None,
            embedding_model: None,
            provenance: None,
            extra_json: None,
            memory_kind: MemoryKind::Raw,
            subject: None,
            predicate: None,
            object: None,
            episodic_at: None,
            procedural_frequency: None,
            self_contained: None,
            self_contained_findings: None,
        }
    }
}

impl KnowledgeNode {
    /// Create a new knowledge node with the given content
    pub fn new(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            ..Default::default()
        }
    }

    /// Check if this node is currently valid (within temporal bounds)
    pub fn is_valid_at(&self, time: DateTime<Utc>) -> bool {
        let after_start = self.valid_from.map(|t| time >= t).unwrap_or(true);
        let before_end = self.valid_until.map(|t| time <= t).unwrap_or(true);
        after_start && before_end
    }

    /// Where this memory's validity window stands at `at`.
    ///
    /// The window is treated as **half-open** `[valid_from, valid_until)`:
    /// `valid_until` names the instant the claim *stopped* holding, so a window
    /// that ends exactly at `at` has already expired, while one that starts
    /// exactly at `at` has just become true. This differs from
    /// [`Self::is_valid_at`], which still counts the closing instant as valid —
    /// kept as it is because the flag has callers that would change behaviour,
    /// and the two readings only disagree on the boundary instant itself.
    pub fn validity_at(&self, at: DateTime<Utc>) -> ValidityAt {
        // `not yet true` first: a window whose start is after `at` has not
        // opened, even if its end is also already behind it (an inverted window
        // is never open, and "has not opened" is the honest reading of that).
        if self.valid_from.is_some_and(|from| from > at) {
            return ValidityAt::NotYetTrue;
        }
        if self.valid_until.is_some_and(|until| until <= at) {
            return ValidityAt::Expired;
        }
        if self.valid_from.is_none() && self.valid_until.is_none() {
            return ValidityAt::Unbounded;
        }
        ValidityAt::True
    }

    /// Check if this node is currently valid (now)
    pub fn is_currently_valid(&self) -> bool {
        self.is_valid_at(Utc::now())
    }

    /// Check if this node is due for review
    pub fn is_due(&self) -> bool {
        self.next_review.map(|t| t <= Utc::now()).unwrap_or(true)
    }

    /// Get the parsed node type
    pub fn get_node_type(&self) -> NodeType {
        NodeType::parse_name(&self.node_type)
    }

    /// Bayesian confidence estimate from Beta(1 + useful, 1 + retrieved - useful).
    /// Returns 95% credible interval and posterior mean.
    pub fn confidence(&self) -> super::ConfidenceEstimate {
        super::ConfidenceEstimate::from_counts(
            self.times_retrieved.unwrap_or(0),
            self.times_useful.unwrap_or(0),
        )
    }

    /// Classify this memory into Tulving's memory systems (episodic/semantic/procedural).
    /// Inferred from `node_type`.
    pub fn memory_system(&self) -> super::MemorySystem {
        match self.get_node_type() {
            NodeType::Event | NodeType::Quote => super::MemorySystem::Episodic,
            NodeType::Procedure | NodeType::Code => super::MemorySystem::Procedural,
            _ => super::MemorySystem::Semantic,
        }
    }

    /// Infer epistemic status from node type, tags, and content signals.
    ///
    /// Hindsight's World/Experience/Observation/Opinion classification helps
    /// the agent calibrate trust in retrieved memories.
    pub fn epistemic_status(&self) -> super::EpistemicStatus {
        let lower_content = self.content.to_lowercase();
        let tags_lower: Vec<String> = self.tags.iter().map(|t| t.to_lowercase()).collect();

        if tags_lower
            .iter()
            .any(|t| t == "preference" || t == "opinion")
        {
            return super::EpistemicStatus::Opinion;
        }
        if tags_lower
            .iter()
            .any(|t| t == "pattern" || t == "observation")
        {
            return super::EpistemicStatus::Observation;
        }

        if lower_content.starts_with("i think")
            || lower_content.starts_with("i prefer")
            || lower_content.starts_with("i believe")
            || lower_content.starts_with("imo ")
            || lower_content.contains("in my opinion")
        {
            return super::EpistemicStatus::Opinion;
        }

        if lower_content.starts_with("i noticed")
            || lower_content.starts_with("it seems")
            || lower_content.starts_with("it appears")
            || lower_content.contains("pattern:")
        {
            return super::EpistemicStatus::Observation;
        }

        match self.get_node_type() {
            NodeType::Event | NodeType::Quote => super::EpistemicStatus::Experience,
            NodeType::Insight => super::EpistemicStatus::Observation,
            _ => super::EpistemicStatus::World,
        }
    }
}

// ============================================================================
// INPUT TYPES
// ============================================================================

/// Input for creating a new memory
///
/// Uses `deny_unknown_fields` to prevent field injection attacks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct IngestInput {
    /// The content to memorize
    pub content: String,
    /// Type of knowledge (fact, concept, procedure, etc.)
    pub node_type: String,
    /// Source of the knowledge
    pub source: Option<String>,
    /// Sentiment polarity (-1.0 to 1.0)
    #[serde(default)]
    pub sentiment_score: f64,
    /// Sentiment intensity (0.0 to 1.0)
    #[serde(default)]
    pub sentiment_magnitude: f64,
    /// Tags for categorization
    #[serde(default)]
    pub tags: Vec<String>,
    /// When this knowledge becomes valid
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<DateTime<Utc>>,
    /// When this knowledge stops being valid
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<DateTime<Utc>>,
    /// Structured provenance metadata (JSON): session_id, agent, derived_from, etc.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provenance: Option<serde_json::Value>,
    /// Free-form JSON for typed extensions (e.g. structured decision payload
    /// under `extra_json.decision`). Persisted verbatim to the `extra_json`
    /// column added by migration v12.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra_json: Option<serde_json::Value>,

    // ========== Typed Memory ==========
    /// Memory kind. Defaults to `Raw`; extractors set a specific kind.
    #[serde(default)]
    pub memory_kind: MemoryKind,
    /// Subject for non-Raw kinds (proper noun like "Caroline"). Optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Predicate for semantic facts ("lives in"). Optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub predicate: Option<String>,
    /// Object for semantic facts ("Berlin"). Optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Absolute event timestamp for episodic memories.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub episodic_at: Option<DateTime<Utc>>,
    /// Frequency descriptor for procedural memories ("weekly", "every Tuesday").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub procedural_frequency: Option<String>,

    // ========== Write-time gate results ==========
    /// What the self-containedness gate said about this content, persisted with
    /// the memory so a flagged entry stays findable after the response is gone.
    /// `None` means the gate did not run, which is not the same as "passed".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub self_contained: Option<bool>,
    /// The findings behind a `false` marker, verbatim.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub self_contained_findings: Option<serde_json::Value>,
    /// Who is writing, recorded on the `memory_revisions` row this write
    /// appends. The storage layer knows the *what*; only the caller (an MCP
    /// tool holding `agent` and `session_id`) knows the *who*, so it travels
    /// with the write request instead of being guessed back out of provenance.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<String>,
    /// Code anchors: where this memory's claims about code can be re-checked.
    ///
    /// Paths and line numbers belong here and **not** in `content`, because a
    /// path inside the text is read as fact forever while it silently drifts to
    /// an old copy or to nothing. An anchor carries the revision and the symbol
    /// that make the reference checkable, and the verdict travels with it
    /// because the write path already resolved it to compute the content hash.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub anchors: Vec<crate::code_refs::IngestAnchor>,
}

impl Default for IngestInput {
    fn default() -> Self {
        Self {
            content: String::new(),
            node_type: "fact".to_string(),
            source: None,
            sentiment_score: 0.0,
            sentiment_magnitude: 0.0,
            tags: vec![],
            valid_from: None,
            valid_until: None,
            provenance: None,
            extra_json: None,
            memory_kind: MemoryKind::Raw,
            subject: None,
            predicate: None,
            object: None,
            episodic_at: None,
            procedural_frequency: None,
            self_contained: None,
            self_contained_findings: None,
            actor: None,
            anchors: vec![],
        }
    }
}

/// Search mode for recall queries
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum SearchMode {
    /// Keyword search only (FTS5/BM25)
    Keyword,
    /// Semantic search only (embeddings)
    Semantic,
    /// Hybrid search with RRF fusion (default, best results)
    #[default]
    Hybrid,
}

/// Input for recalling memories
///
/// Uses `deny_unknown_fields` to prevent field injection attacks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RecallInput {
    /// Search query
    pub query: String,
    /// Maximum results to return
    pub limit: i32,
    /// Minimum retention strength (0.0 to 1.0)
    #[serde(default)]
    pub min_retention: f64,
    /// Search mode (keyword, semantic, or hybrid)
    #[serde(default)]
    pub search_mode: SearchMode,
    /// Only return results valid at this time
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_at: Option<DateTime<Utc>>,
}

impl Default for RecallInput {
    fn default() -> Self {
        Self {
            query: String::new(),
            limit: 10,
            min_retention: 0.0,
            search_mode: SearchMode::Hybrid,
            valid_at: None,
        }
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_node_type_roundtrip() {
        for node_type in [
            NodeType::Fact,
            NodeType::Concept,
            NodeType::Procedure,
            NodeType::Event,
            NodeType::Code,
        ] {
            assert_eq!(NodeType::parse_name(node_type.as_str()), node_type);
        }
    }

    /// The valid-time window is half-open at its end: `valid_until` names the
    /// instant the claim *stopped* holding. This is the reading the as-of read
    /// path documents, and the boundary is exactly where the three conventions
    /// in this repository disagree, so it is pinned here.
    #[test]
    fn validity_at_treats_valid_until_as_the_instant_the_claim_stopped_holding() {
        let at = Utc::now();

        let mut node = KnowledgeNode::default();
        assert_eq!(
            node.validity_at(at),
            ValidityAt::Unbounded,
            "no window means the claim carried no validity bound at all"
        );

        node.valid_from = Some(at);
        assert_eq!(
            node.validity_at(at),
            ValidityAt::True,
            "a window that opens exactly at the instant has just become true"
        );

        node.valid_until = Some(at);
        assert_eq!(
            node.validity_at(at),
            ValidityAt::Expired,
            "a window that closes exactly at the instant has already stopped holding"
        );
        assert!(
            node.is_valid_at(at),
            "test premise: `is_valid_at` keeps the closing instant, which is the \
             documented difference between the two readings"
        );

        node.valid_from = Some(at + chrono::Duration::seconds(1));
        node.valid_until = None;
        assert_eq!(node.validity_at(at), ValidityAt::NotYetTrue);

        node.valid_from = None;
        node.valid_until = Some(at + chrono::Duration::seconds(1));
        assert_eq!(node.validity_at(at), ValidityAt::True);
    }

    #[test]
    fn test_memory_kind_roundtrip() {
        for kind in [
            MemoryKind::Raw,
            MemoryKind::Semantic,
            MemoryKind::Episodic,
            MemoryKind::Procedural,
            MemoryKind::Aggregate,
        ] {
            assert_eq!(MemoryKind::parse(kind.as_str()), kind);
        }
        // Unknown / malformed strings fall back to Raw for back-compat.
        assert_eq!(MemoryKind::parse(""), MemoryKind::Raw);
        assert_eq!(MemoryKind::parse("garbage"), MemoryKind::Raw);
        assert_eq!(MemoryKind::parse("SEMANTIC"), MemoryKind::Semantic);
    }

    #[test]
    fn test_memory_kind_default_is_raw() {
        let node = KnowledgeNode::default();
        assert_eq!(node.memory_kind, MemoryKind::Raw);
        assert!(node.subject.is_none());
        assert!(node.episodic_at.is_none());
        assert!(node.procedural_frequency.is_none());

        let input = IngestInput::default();
        assert_eq!(input.memory_kind, MemoryKind::Raw);
        assert!(input.subject.is_none());
    }

    #[test]
    fn test_memory_kind_serde() {
        use serde_json;
        let json = serde_json::to_string(&MemoryKind::Episodic).unwrap();
        assert_eq!(json, "\"episodic\"");
        let parsed: MemoryKind = serde_json::from_str("\"semantic\"").unwrap();
        assert_eq!(parsed, MemoryKind::Semantic);
    }

    #[test]
    fn test_knowledge_node_default() {
        let node = KnowledgeNode::default();
        assert!(node.id.is_empty());
        assert_eq!(node.node_type, "fact");
        assert!(node.is_due());
        assert!(node.is_currently_valid());
    }

    #[test]
    fn test_temporal_validity() {
        let mut node = KnowledgeNode::default();
        let now = Utc::now();

        // No bounds = always valid
        assert!(node.is_valid_at(now));

        // Set future valid_from = not valid now
        node.valid_from = Some(now + chrono::Duration::days(1));
        assert!(!node.is_valid_at(now));

        // Set past valid_from = valid now
        node.valid_from = Some(now - chrono::Duration::days(1));
        assert!(node.is_valid_at(now));

        // Set past valid_until = not valid now
        node.valid_until = Some(now - chrono::Duration::hours(1));
        assert!(!node.is_valid_at(now));
    }

    #[test]
    fn test_ingest_input_deny_unknown_fields() {
        // Valid input should parse
        let json = r#"{"content": "test", "nodeType": "fact", "tags": []}"#;
        let result: Result<IngestInput, _> = serde_json::from_str(json);
        assert!(result.is_ok());

        // Unknown field should fail (security feature)
        let json_with_unknown =
            r#"{"content": "test", "nodeType": "fact", "tags": [], "malicious_field": "attack"}"#;
        let result: Result<IngestInput, _> = serde_json::from_str(json_with_unknown);
        assert!(result.is_err());
    }
}
